import os          
from time import sleep as ts
from linecache import getline as gl
from webbrowser import open_new_tab as nw
cext = 'config_crome_extensions.txt'
fext = 'config_firefox_extensions.txt'
cob = 'config_blank.txt'
co = 'config_overclocking.txt'
cg = 'config_games.txt'
od = 'Opening Download(s) in 3 sec...'
pe = 'press enter to choose another option...'
p = print
def cls():                                         
    os.system('cls' if os.name=='nt' else 'clear')     
def cb() :
    os.system("taskkill /im brave.exe /f") 
    cls()
    os.system("taskkill /im msedge.exe /f") 
    cls()
    os.system("taskkill /im chrome.exe /f") 
    cls()
    os.system("taskkill /im firefox.exe /f") 
    cls()
cb()
def sm():
    cls()
    p ('[Choose a number corresponding to an option]')  
    p ('OPTIONS: \n \n \n')
    p ('[1] Tools for after blank windows installation')
    p ('[2] Game Launchers')
    p ('[3] Internet (browsers etc.)')
    p ('[4] Utilities')
    p ('[5] Overclocking')
    p ('[6] Usefull Extensions (browsers)')
    p ('[9] my discord :)')
    Main = input()
    if Main == '1' :        
        cls()
        p(od)
        ts (3)
        nw(gl(cob, 1))
        nw(gl(cob, 2))
        nw(gl(cob, 3))
        nw(gl(cob, 4))
        nw(gl(cob, 5))
        nw(gl(cob, 6))
        nw(gl(cob, 7))
        nw(gl(cob, 8))
        nw(gl(cob, 9))
        nw(gl(cob, 10))
        pse = input(pe)
        sm()
    elif Main == '2' :      
        cls()
        p(od)
        ts (3)
        nw(gl(cg, 1))
        nw(gl(cg, 2))
        nw(gl(cg, 3))
        nw(gl(cg, 4))
        nw(gl(cg, 5))
        nw(gl(cg, 6))
        nw(gl(cg, 7))
        nw(gl(cg, 8))
        nw(gl(cg, 9))
        nw(gl(cg, 10))
        pse = input(pe)
        sm()
    elif Main == '3' :    
        cls()
        p ('Choose wich browser... \n\n\n')
        p ('[1] Brve')
        p ('[2] firefox')
        p ('[3] TOR')
        p ('[4] google chrome')
        Brch = input()
        if Brch == '1':
            cls()
            p(od)
            ts (3)
            nw('https://brave.com/download/')
            pse = input(pe)
            sm()
        elif Brch == '2':
            cls()
            p(od)
            ts (3)
            nw('https://www.mozilla.org/nl/firefox/new/')
            pse = input(pe)
            sm()
        elif Brch == '3':
            cls()
            p(od)
            ts (3)
            nw('https://www.torproject.org/download/')
            pse = input(pe)
            sm()
        elif Brch == '4':
            cls()
            p(od)
            ts (3)
            nw('https://www.google.com/intl/en/chrome/')
            pse = input(pe)
            sm()
    elif Main == '4' :
        cls()
        p ('Choose wich utility... \n\n\n')
        p ('[1] qBittorrent')
        p ('[2] WinDirStat')
        p ('[3] Malwarebytes')
        p ('[4] visual Studio')
        uch = input()
        if uch == '1':
            cls()
            p(od)
            ts (3)
            nw('https://www.qbittorrent.org/download.php')
            pse = input(pe)
            sm()
        elif uch == '2':
            cls()
            p(od)
            ts (3)
            nw('https://www.fosshub.com/WinDirStat.html')
            pse = input(pe)
            sm()
        elif uch == '3':
            cls()
            p(od)
            ts (3)
            nw('https://nl.malwarebytes.com/mwb-download/')
            pse = input(pe)
            sm()
        elif uch == '4':
            cls()
            p(od)
            ts (3)
            nw('https://code.visualstudio.com/download')
            pse = input(pe)
            sm()
    elif Main == '5' :
        cls()
        p(od)
        ts (3)
        nw(gl(co, 1))
        nw(gl(co, 2))
        nw(gl(co, 3))
        nw(gl(co, 4))
        nw(gl(co, 5))
        nw(gl(co, 6))
        nw(gl(co, 7))
        nw(gl(co, 8))
        nw(gl(co, 9))
        nw(gl(co, 10))
        pse = input(pe)
        sm()
    elif Main == '6' :
        cls()
        p('Choose your browser: \n\n\n')
        p('[1] Any chromium based browser')
        p('[2] Firefox (tor)')
        ExtOpt = input()
        if ExtOpt == '1':
            cls()
            p(od)
            ts (3)
            nw(gl(cext, 1))
            nw(gl(cext, 2))
            nw(gl(cext, 3))
            nw(gl(cext, 4))
            nw(gl(cext, 5))
            nw(gl(cext, 6))
            nw(gl(cext, 7))
            nw(gl(cext, 8))
            nw(gl(cext, 9))
            nw(gl(cext, 10))
            pse = input(pe)
            sm()
        elif ExtOpt == '2':
            cls()
            p(od)
            ts (3)
            nw(gl(fext, 1))
            nw(gl(fext, 2))
            nw(gl(fext, 3))
            nw(gl(fext, 4))
            nw(gl(fext, 5))
            nw(gl(fext, 6))
            nw(gl(fext, 7))
            nw(gl(fext, 8))
            nw(gl(fext, 9))
            nw(gl(fext, 10))
            pse = input(pe)
            sm()
        pse = input(pe)
        sm()
    elif Main == '9' :
        cls()
        p('Opening my site in 3 sec...')
        ts (3)
        nw('https://sites.google.com/view/district14/homepage')
        pse = input(pe)
        sm()
        pse = input(pe)
        sm()
p('made by me :)')
ts (1)
cls()
sm()
        

